openapi: 3.0.0
info:
  title: Array Test API
  version: 1.0.0
paths:
  /test:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArrayTestRequest"
      responses:
        '200':
          description: OK
components:
  schemas:
    ArrayTestRequest:
      type: object
      properties:
        requiredStringArray:
          type: array
          items:
            type: string
            minLength: 2
            maxLength: 50
          minItems: 1
          maxItems: 10
        optionalStringArray:
          type: array
          items:
            type: string
            minLength: 1
          maxItems: 5
        requiredIntArray:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 100
          minItems: 2
        emptyAllowedArray:
          type: array
          items:
            type: string
          minItems: 0
          maxItems: 3
        objectArray:
          type: array
          items:
            $ref: "#/components/schemas/NestedObject"
      required:
        - requiredStringArray
        - requiredIntArray
    NestedObject:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id