// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package example

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Pet struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

type Pets []Pet
