openapi: 3.0.0
info:
  title: Minimal Array Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    TestArray:
      type: array
      items:
        type: string
      minItems: 1
      maxItems: 3