openapi: 3.0.0
info:
  title: Simple Array Test
  version: 1.0.0
paths:
  /test:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimpleArrayTest"
      responses:
        '200':
          description: OK
components:
  schemas:
    SimpleArrayTest:
      type: object
      properties:
        optionalArray:
          type: array
          items:
            type: string
            minLength: 2
            maxLength: 10
          minItems: 1
          maxItems: 5