openapi: 3.0.0
info:
  title: Bearer Token Test API
  version: 1.0.0
paths:
  /bearer-endpoint:
    post:
      tags:
        - auth
      summary: Endpoint with Bearer token
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer 