openapi: 3.0.0
info:
  title: Security Skip Example API
  version: 1.0.0
paths:
  /secure-endpoint:
    get:
      tags:
        - auth
      summary: Secure endpoint with normal security check
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
  /semi-secure-endpoint:
    get:
      tags:
        - auth
      summary: Endpoint that parses but skips security validation
      x-go-skip-security-check: true
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  apiKey:
                    type: string
        '400':
          description: Bad Request
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key 