// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package arraytest

import (
	"encoding/json"
	"fmt"
)

type arrayTestRequest struct {
	EmptyAllowedArray   []string       `json:"emptyAllowedArray"`
	ObjectArray         []NestedObject `json:"objectArray"`
	OptionalStringArray []string       `json:"optionalStringArray"`
	RequiredIntArray    *[]int         `json:"requiredIntArray"`
	RequiredStringArray *[]string      `json:"requiredStringArray"`
}

type ArrayTestRequest struct {
	EmptyAllowedArray   []string       `json:"emptyAllowedArray"`
	ObjectArray         []NestedObject `json:"objectArray"`
	OptionalStringArray []string       `json:"optionalStringArray"`
	RequiredIntArray    []int          `json:"requiredIntArray"`
	RequiredStringArray []string       `json:"requiredStringArray"`
}

func (body *ArrayTestRequest) UnmarshalJSON(data []byte) error {
	var value arrayTestRequest
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.EmptyAllowedArray = value.EmptyAllowedArray
	body.ObjectArray = value.ObjectArray
	body.OptionalStringArray = value.OptionalStringArray

	if value.RequiredIntArray == nil {
		return fmt.Errorf("requiredIntArray is required")
	}

	body.RequiredIntArray = *value.RequiredIntArray

	if value.RequiredStringArray == nil {
		return fmt.Errorf("requiredStringArray is required")
	}

	body.RequiredStringArray = *value.RequiredStringArray

	return nil
}
func (body ArrayTestRequest) Validate() error {
	return nil
}

type nestedObject struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type NestedObject struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (body *NestedObject) UnmarshalJSON(data []byte) error {
	var value nestedObject
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.Name = value.Name

	if value.ID == nil {
		return fmt.Errorf("id is required")
	}

	body.ID = *value.ID

	return nil
}
func (body NestedObject) Validate() error {
	return nil
}
