// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package arraytest

import "net/http"

var spec = []byte("{\"components\":{\"schemas\":{\"ArrayTestRequest\":{\"properties\":{\"emptyAllowedArray\":{\"items\":{\"type\":\"string\"},\"maxItems\":3,\"type\":\"array\"},\"objectArray\":{\"items\":{\"$ref\":\"#/components/schemas/NestedObject\"},\"type\":\"array\"},\"optionalStringArray\":{\"items\":{\"minLength\":1,\"type\":\"string\"},\"maxItems\":5,\"type\":\"array\"},\"requiredIntArray\":{\"items\":{\"maximum\":100,\"minimum\":1,\"type\":\"integer\"},\"minItems\":2,\"type\":\"array\"},\"requiredStringArray\":{\"items\":{\"maxLength\":50,\"minLength\":2,\"type\":\"string\"},\"maxItems\":10,\"minItems\":1,\"type\":\"array\"}},\"required\":[\"requiredStringArray\",\"requiredIntArray\"],\"type\":\"object\"},\"NestedObject\":{\"properties\":{\"id\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"required\":[\"id\"],\"type\":\"object\"}}},\"info\":{\"title\":\"Array Test API\",\"version\":\"1.0.0\"},\"openapi\":\"3.0.0\",\"paths\":{\"/test\":{\"post\":{\"requestBody\":{\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/ArrayTestRequest\"}}}},\"responses\":{\"200\":{\"description\":\"OK\"}}}}}}")

func Spec(w http.ResponseWriter, _ *http.Request) {
	w.Header().Add("Content-Type", "application/json")
	w.Write(spec)
}
