// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package simplearray

type SimpleArrayTest struct {
	OptionalArray []string `json:"optionalArray"`
}

func (S SimpleArrayTest) Validate() error {
	return nil
}
