// This file is generated by github.com/mikekonan/go-oas3. DO NOT EDIT.

package simplearray

import (
	"context"
	"encoding/json"
	chi "github.com/go-chi/chi/v5"
	"net/http"
	"slices"
)

type Hooks struct {
	RequestSecurityParseFailed    func(*http.Request, string, RequestProcessingResult)
	RequestSecurityParseCompleted func(*http.Request, string)
	RequestSecurityCheckFailed    func(*http.Request, string, string, RequestProcessingResult)
	RequestSecurityCheckCompleted func(*http.Request, string, string)
	RequestBodyUnmarshalFailed    func(*http.Request, string, RequestProcessingResult)
	RequestHeaderParseFailed      func(*http.Request, string, string, RequestProcessingResult)
	RequestPathParseFailed        func(*http.Request, string, string, RequestProcessingResult)
	RequestQueryParseFailed       func(*http.Request, string, string, RequestProcessingResult)
	RequestBodyValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestHeaderValidationFailed func(*http.Request, string, RequestProcessingResult)
	RequestPathValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestQueryValidationFailed  func(*http.Request, string, RequestProcessingResult)
	RequestBodyUnmarshalCompleted func(*http.Request, string)
	RequestHeaderParseCompleted   func(*http.Request, string)
	RequestPathParseCompleted     func(*http.Request, string)
	RequestQueryParseCompleted    func(*http.Request, string)
	RequestParseCompleted         func(*http.Request, string)
	RequestProcessingCompleted    func(*http.Request, string)
	RequestRedirectStarted        func(*http.Request, string, string)
	ResponseBodyMarshalCompleted  func(*http.Request, string)
	ResponseBodyWriteCompleted    func(*http.Request, string, int)
	ResponseBodyMarshalFailed     func(http.ResponseWriter, *http.Request, string, error)
	ResponseBodyWriteFailed       func(*http.Request, string, int, error)
	ServiceCompleted              func(*http.Request, string)
}

type requestProcessingResultType uint8

const (
	BodyUnmarshalFailed requestProcessingResultType = iota + 1
	BodyValidationFailed
	HeaderParseFailed
	HeaderValidationFailed
	QueryParseFailed
	QueryValidationFailed
	PathParseFailed
	PathValidationFailed
	SecurityParseFailed
	SecurityCheckFailed
	ParseSucceed
)

type RequestProcessingResult struct {
	error error
	typee requestProcessingResultType
}

func NewRequestProcessingResult(t requestProcessingResultType, err error) RequestProcessingResult {
	return RequestProcessingResult{
		error: err,
		typee: t,
	}
}

func (r RequestProcessingResult) Type() requestProcessingResultType {
	return r.typee
}

func (r RequestProcessingResult) Err() error {
	return r.error
}

func DefaultHandler(impl DefaultService, r chi.Router, hooks *Hooks) http.Handler {
	router := &defaultRouter{router: r, service: impl, hooks: hooks}

	router.mount()

	return router.router
}

type defaultRouter struct {
	router  chi.Router
	service DefaultService
	hooks   *Hooks
}

func (router *defaultRouter) mount() {
	router.router.Post("/test", router.PostTest)
}

func (router *defaultRouter) parsePostTestRequest(r *http.Request) (request PostTestRequest) {
	request.ProcessingResult = RequestProcessingResult{typee: ParseSucceed}

	var (
		body      SimpleArrayTest
		decodeErr error
	)
	decodeErr = json.NewDecoder(r.Body).Decode(&body)
	if decodeErr != nil {
		request.ProcessingResult = RequestProcessingResult{error: decodeErr, typee: BodyUnmarshalFailed}
		if router.hooks.RequestBodyUnmarshalFailed != nil {
			router.hooks.RequestBodyUnmarshalFailed(r, "PostTest", request.ProcessingResult)

			return
		}

		return
	}

	request.Body = body

	if router.hooks.RequestBodyUnmarshalCompleted != nil {
		router.hooks.RequestBodyUnmarshalCompleted(r, "PostTest")
	}

	if err := request.Body.Validate(); err != nil {
		request.ProcessingResult = RequestProcessingResult{error: err, typee: BodyValidationFailed}
		if router.hooks.RequestBodyValidationFailed != nil {
			router.hooks.RequestBodyValidationFailed(r, "PostTest", request.ProcessingResult)
		}

		return
	}

	if router.hooks.RequestParseCompleted != nil {
		router.hooks.RequestParseCompleted(r, "PostTest")
	}

	return
}

func (router *defaultRouter) PostTest(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()

	response := router.service.PostTest(r.Context(), router.parsePostTestRequest(r))

	for header, value := range response.headers() {
		w.Header().Set(header, value)
	}

	for _, c := range response.cookies() {
		cookie := c
		http.SetCookie(w, &cookie)
	}

	if slices.Contains([]int{301, 302, 303, 307, 308}, response.statusCode()) && response.redirectURL() != "" {
		if router.hooks.RequestRedirectStarted != nil {
			router.hooks.RequestRedirectStarted(r, "PostTest", response.redirectURL())
		}

		http.Redirect(w, r, response.redirectURL(), response.statusCode())

		if router.hooks.ServiceCompleted != nil {
			router.hooks.ServiceCompleted(r, "PostTest")
		}

		return
	}

	if router.hooks.RequestProcessingCompleted != nil {
		router.hooks.RequestProcessingCompleted(r, "PostTest")
	}

	w.WriteHeader(response.statusCode())

	if router.hooks.ServiceCompleted != nil {
		router.hooks.ServiceCompleted(r, "PostTest")
	}
}

type response struct {
	statusCode  int
	body        interface{}
	bodyRaw     []byte
	contentType string
	redirectURL string
	headers     map[string]string
	cookies     []http.Cookie
}

type responseInterface interface {
	statusCode() int
	body() interface{}
	bodyRaw() []byte
	contentType() string
	redirectURL() string
	cookies() []http.Cookie
	headers() map[string]string
}

type PostTestResponse interface {
	responseInterface
	postTestResponse()
}

type postTestResponse struct {
	response
}

func (postTestResponse) postTestResponse() {}

func (response postTestResponse) statusCode() int {
	return response.response.statusCode
}

func (response postTestResponse) body() interface{} {
	return response.response.body
}

func (response postTestResponse) bodyRaw() []byte {
	return response.response.bodyRaw
}

func (response postTestResponse) contentType() string {
	return response.response.contentType
}

func (response postTestResponse) redirectURL() string {
	return response.response.redirectURL
}

func (response postTestResponse) headers() map[string]string {
	return response.response.headers
}

func (response postTestResponse) cookies() []http.Cookie {
	return response.response.cookies
}

type postTestStatusCodeResponseBuilder struct {
	response
}

func PostTestResponseBuilder() *postTestStatusCodeResponseBuilder {
	return new(postTestStatusCodeResponseBuilder)
}

func (builder *postTestStatusCodeResponseBuilder) StatusCode200() *PostTest200ResponseBuilder {
	builder.response.statusCode = 200

	return &PostTest200ResponseBuilder{response: builder.response}
}

type PostTest200ResponseBuilder struct {
	response
}

func (builder *PostTest200ResponseBuilder) Build() PostTestResponse {
	return postTestResponse{response: builder.response}
}

type DefaultService interface {
	PostTest(context.Context, PostTestRequest) PostTestResponse
}

type PostTestRequest struct {
	Body             SimpleArrayTest
	ProcessingResult RequestProcessingResult
}

type SecurityScheme string

const ()

type securityProcessor struct {
	scheme  SecurityScheme
	extract func(r *http.Request) (string, string, bool)
	handle  func(r *http.Request, scheme SecurityScheme, name string, value string) error
}

var securityExtractorsFuncs = map[SecurityScheme]func(r *http.Request) (string, string, bool){}

type SecuritySchemas interface{}

type SecurityCheckResult struct {
	Scheme SecurityScheme
	Value  string
}
